In [1]:
# Import
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load in the medquad dataset 
medquad_df = pd.read_csv('../data/medquad.csv')
medquad_df.head()

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...,NIHSeniorHealth,Glaucoma
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ...",NIHSeniorHealth,Glaucoma
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma

In [3]:
# Get the number of rows in dataset 
medquad_df.shape[0]

16412

In [4]:
# Get any info regarding the medquad dataset
medquad_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16412 entries, 0 to 16411
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   question    16412 non-null  object
 1   answer      16407 non-null  object
 2   source      16412 non-null  object
 3   focus_area  16398 non-null  object
dtypes: object(4)
memory usage: 513.0+ KB

In [5]:
# Describe the medquad dataset
medquad_df.describe()

,question,answer,source,focus_area
count,16412,16407,16412,16398
unique,14984,15817,9,5126
top,What causes Causes of Diabetes ?,This condition is inherited in an autosomal re...,GHR,Breast Cancer
freq,20,348,5430,53

In [6]:
# Remove source and focus_area columns from medquad dataset
medquad_df.drop(columns=['source', 'focus_area'], inplace=True)
medquad_df.head()

,question,answer
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea..."
2,What are the symptoms of Glaucoma ?,Symptoms of Glaucoma Glaucoma can develop in ...
3,What are the treatments for Glaucoma ?,"Although open-angle glaucoma cannot be cured, ..."
4,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...

In [7]:
# Check for missing values
medquad_df.isnull().sum()

question    0
answer      5
dtype: int64

In [8]:
# Remove all rows with missing values
medquad_df.dropna(inplace=True)
medquad_df.shape[0]

16407

In [9]:
# Lowercase all question and answer text
medquad_df['question'] = medquad_df['question'].str.lower()
medquad_df['answer'] = medquad_df['answer'].str.lower()
medquad_df.head()

,question,answer
0,what is (are) glaucoma ?,glaucoma is a group of diseases that can damag...
1,what causes glaucoma ?,"nearly 2.7 million people have glaucoma, a lea..."
2,what are the symptoms of glaucoma ?,symptoms of glaucoma glaucoma can develop in ...
3,what are the treatments for glaucoma ?,"although open-angle glaucoma cannot be cured, ..."
4,what is (are) glaucoma ?,glaucoma is a group of diseases that can damag...

In [10]:
# Check for duplicates
medquad_df.duplicated().sum()

np.int64(48)

In [11]:
# Remove all duplicate rows
medquad_df.drop_duplicates(inplace=True)
medquad_df.shape[0]

16359

In [12]:
medquad_df.to_csv("medquad_cleaned.csv", index=False)